jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    steps:
      - name: ⬇️ Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: Nextjs-site

      - name: 🗝️ Set up Azure CLI environment variables
        run: |
          export ARM_CLIENT_ID=${{ secrets.AZURE_CREDENTIALS.appId }}
          export ARM_CLIENT_SECRET=${{ secrets.AZURE_CREDENTIALS.password }}
          export ARM_TENANT_ID=${{ secrets.AZURE_CREDENTIALS.tenant }}

      - name: 🔍 Diagnostics
        run: |
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"

      - name: 🚀 Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          package: ${{ github.workspace }}/Nextjs-site.zip

      - name: 🧹 Cleanup
        run: rm ${{ github.workspace }}/Nextjs-site.zip
